export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";